### ISSUE TITLE
Env variable ENABLE defined in sysconfig not used

### ISSUE THREAD

**Issue by christophlehmann** [entercloudsuite/ansible-prometheus-exporter#10]

**Comment by AttilioGreco** [comment]
Can I close the issues, or can you give me some details?

**Comment by karlskewes** [comment]
I think it's from this:
```
ansible-prometheus-exporter$ cat templates/etc/sysconfig/default_template.j2
{% if prometheus_exporter_enabled_collectors is defined and prometheus_exporter_enabled_collectors %}
ENABLE="{% for item in prometheus_exporter_enabled_collectors -%}  --collector.{{item+" "}} {%- endfor %}"
{% else %}
ENABLE=" "
{% endif %}
```
The second statement isn't required I think: `ENABLE= " "`
Same with DISABLE.

Whilst we're at it, this variable in defaults is probably not required either, unless entercloudsuite requires it for another role?
`defaults/main.yml:8:prometheus_exporter_nead_sysconfig: false`
